[repositories]
rugpi-extra = { git = "https://github.com/silitics/rugpi-extra.git" }

[images.rpi4]
layer = "customized"
# Include the firmware update for Raspberry Pi 4 and CM4.
include_firmware = "pi4"

[images.tryboot]
layer = "customized"
